[advisories]
yanked = "warn"
unmaintained = "none"
ignore = []

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "CC0-1.0",
  "Unicode-3.0"
]
confidence-threshold = 0.8

[licenses.private]
ignore = false
registries = []

[graph]
targets = [
  # { triple = "x86_64-unknown-linux-musl" },
  # { triple = "wasm32-unknown-unknown", features = ["atomics"] },
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
