name: Rust CI

on:
  push:
    branches: [rust-based]
  pull_request:
    branches: [rust-based]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # 关键修改：递归初始化子模块

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose

    # 可选：添加子模块状态验证
    - name: Verify submodules
      run: git submodule status
